name: Probar página

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests'
        required: true
        default: chromium
        type: choice
        options:
        - firefox
        - chromium
        - webkit

env:
  TEST_BROWSER: ${{ github.event.inputs.browser }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: python -m pip install -r test-requirements.txt
      - run: python -m playwright install
      - name: Run tests (pytest)
        run: |
          mkdir -p screenshots
          pytest --tracing=retain-on-failure --browser=${{ env.TEST_BROWSER }}

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
